Issue #188: add tests for road styles.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -15,7 +15,7 @@ else
 fi
 
 # Check format, lint, run static analyzer.
-data/githooks/pre-commit || { echo "FAIL"; exit 1; }
+.githooks/pre-commit || { echo "FAIL"; exit 1; }
 
 # Unit tests with pytest.
 echo "Run tests with pytest..."
